INSERT INTO public.themes (id, section_id, title) VALUES (1, 1, 'Тема 1. Предмет и метод бухгалтерского учета');
INSERT INTO public.themes (id, section_id, title) VALUES (2, 1, 'Тема 2. Бухгалтерский баланс');
INSERT INTO public.themes (id, section_id, title) VALUES (3, 1, 'Тема 3. Система счетов и двойная запись');
INSERT INTO public.themes (id, section_id, title) VALUES (4, 1, 'Тема 4. Стоимостное измерение и оценка объектов бухгалтерского учета');
INSERT INTO public.themes (id, section_id, title) VALUES (5, 1, 'Тема 5. Документация и инвентаризация');
INSERT INTO public.themes (id, section_id, title) VALUES (6, 1, 'Тема 6. Обобщение учетной информации для составления бухгалтерской отчетности');
INSERT INTO public.themes (id, section_id, title) VALUES (7, 2, 'Тема 1. Основы бухгалтерского (финансового) учета');
INSERT INTO public.themes (id, section_id, title) VALUES (8, 2, 'Тема 4. Учет финансовых вложений');
INSERT INTO public.themes (id, section_id, title) VALUES (9, 2, 'Тема 7. Учет выпуска и продажи продукции');
INSERT INTO public.themes (id, section_id, title) VALUES (10, 2, 'Тема 8. Учет денежных средств');
INSERT INTO public.themes (id, section_id, title) VALUES (11, 2, 'Тема 9. Учет расчетов по текущим обязательствам');
INSERT INTO public.themes (id, section_id, title) VALUES (12, 2, 'Тема 10. Учет внешнеэкономической деятельности');
INSERT INTO public.themes (id, section_id, title) VALUES (13, 3, 'Тема 1. Федеральный закон «О бухгалтерском учете»');
INSERT INTO public.themes (id, section_id, title) VALUES (14, 3, 'Тема 2. Учетная политика организации (ПБУ 1/98)');
INSERT INTO public.themes (id, section_id, title) VALUES (15, 3, 'Тема 3. Учет договоров (контрактов) на капитальное строительство (ПБУ 2/94)');
INSERT INTO public.themes (id, section_id, title) VALUES (16, 3, 'Тема 4. Учет активов и обязательств, стоимость которых выражена в иностранной валюте (ПБУ 3/2000)');
INSERT INTO public.themes (id, section_id, title) VALUES (17, 3, 'Тема 5. Бухгалтерская отчетность организации (ПБУ 4/99)');
INSERT INTO public.themes (id, section_id, title) VALUES (18, 3, 'Тема 6. Учет материально-производственных запасов (ПБУ 5/01)');
INSERT INTO public.themes (id, section_id, title) VALUES (19, 3, 'Тема 7. Учет основных средств (ПБУ 6/01)');
INSERT INTO public.themes (id, section_id, title) VALUES (20, 3, 'Тема 8. События после отчетной даты (ПБУ 7/98)');
INSERT INTO public.themes (id, section_id, title) VALUES (21, 3, 'Тема 9. Условные факты хозяйственной деятельности (ПБУ 8/01)');
INSERT INTO public.themes (id, section_id, title) VALUES (22, 3, 'Тема 12. Информация об аффилированных лицах (ПБУ 11/2000)');
INSERT INTO public.themes (id, section_id, title) VALUES (23, 3, 'Тема 13. Информация по сегментам (ПБУ 12/2000)');
INSERT INTO public.themes (id, section_id, title) VALUES (24, 3, 'Тема 14. Учет государственной помощи (ПБУ 13/2000)');
INSERT INTO public.themes (id, section_id, title) VALUES (25, 3, 'Тема 15. Учет нематериальных активов (ПБУ 14/2000)');
INSERT INTO public.themes (id, section_id, title) VALUES (26, 3, 'Тема 16. Учет займов и кредитов и затрат по их обслуживанию (ПБУ 15/01)');
INSERT INTO public.themes (id, section_id, title) VALUES (27, 3, 'Тема 17. Информация по прекращаемой деятельности (ПБУ 16/02)');
INSERT INTO public.themes (id, section_id, title) VALUES (28, 3, 'Тема 18. Учет расходов на научно-исследовательские, опытно-конструкторские и технологические работы (ПБУ 17/02)');
INSERT INTO public.themes (id, section_id, title) VALUES (29, 3, 'Тема 19. ❗️ УСТАРЕВШЕЕ ЗАКОНОДАТЕЛЬСТВО ❗️ Учет расчетов по налогу на прибыль (ПБУ 18/02)');
INSERT INTO public.themes (id, section_id, title) VALUES (30, 3, 'Тема 20. Учет финансовых вложений (ПБУ 19/02)');
INSERT INTO public.themes (id, section_id, title) VALUES (31, 3, 'Тема 21. Информация об участии в совместной деятельности (ПБУ 20/03)');
